config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:new, :show, :create] do
    resources :doses, only: [:new, :create]
  end

  root to: 'cocktails#index'
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :find_cocktail, only: [:show]
  
  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<nav class="navbar-lewagon navbar-collapse navbar-brand w-100 d-flex justify-content-between bg-dark my-nav-bar">
  <div class="logo-cocktail avatar ml-3">
    <%= image_tag 'https://s2.glbimg.com/IXTttUns_iyMPAyqmr4X6CCzq4k=/620x850/e.glbimg.com/og/ed/f/original/2018/09/28/drink-piscine-bobardi.jpg', style: 'width: 50px; height: 50px; border-radius: 25px' %>
  </div>
  <div class="link-create-drink">
    <%= link_to 'Admin', rails_admin_path, class: 'btn btn-danger mr-3' %>
    <%= link_to 'Crie seu drink', new_cocktail_path, class: 'btn btn-danger mr-3' %>
  </div>
</nav>

<div class="container d-flex flex-wrap cocktail-index">
  <% @cocktails.each do |cocktail| %>
    <%# <%= link_to cocktail.name, cocktail_path(cocktail)%> 
    <div class="card my-4 mx-4 shadow-lg my-card" style="width: 18rem;">
      <%= cl_image_tag cocktail.photo.key, class: "img-cocktail"%>
      <div class="card-body d-flex justify-content-around">
        <h5 class="card-title"><strong><%= cocktail.name %></strong></h5>
        <%= link_to 'More info', cocktail_path(cocktail), class: 'btn btn-danger' %>
      </div>
    </div>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<div class="d-flex justify-content-center text-white my-5">
  <h1>Crie seu cocktail!</h1>
</div>

<div class="d-flex justify-content-center new-cocktail">
  
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file, class: 'btn btn-danger' %>
    <%= f.submit class: 'btn btn-danger' %>
    <%= link_to 'Voltar', root_path, class: 'btn btn-danger' %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
  <div class="info-geral-cocktail d-flex justify-content-around">
    <div class="name-cocktail text-white">
      <h1><%= @cocktail.name %></h1>
    </div>
  </div>
  <div class="container-all-info d-flex justify-content-around my-5 teste">
        <% @cocktail.doses.each do |dose| %>
        <% if dose.ingredient == nil %>
        <% else %>
          <div class="description bg-white mb-5">
            <div class="container-p d-flex justify-content-around">
              <div class="ingredient ml-3">
                <strong><p>Ing: <%= dose.ingredient.name %></p></strong>
              </div>
              <div class="dose"> 
                <strong><p>Quant: <%= dose.description %></p></strong>
              </div>
              <i><%= link_to '', dose_path(dose), method: :delete, data: { confirm: 'Você quer deletar essa dose?' }, class: 'far fa-trash-alt mr-2' %></i>
          </div>
        <% end %>
    
        <% end %>
    </div>
    

    <div class="d-flex justify-content-center">
      <%= render 'doses/form', class: 'w-100' %> 
    </div>
  </div>
  <div class="container-link-back d-flex justify-content-center">
    <%= link_to 'Voltar a lista', root_path, class: 'btn btn-danger mt-5' %>
  </div>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <div class="container-form d-flex justify-content-center align-items-center flex-column">
    <div class="container-input">
      <%= f.input :description %>
      <%= f.association :ingredient, collection: Ingredient.all %>
    </div>
    <div class="container-link-create-cocktail">
      <%= f.submit 'Criar quantidade', class: 'btn btn-danger' %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body  class='general'>
    <%= yield %>
  </body>
</html>